Changed the import of the Extension class in all example extensions, so that now the Extension class is imported from NumPy (and not directly from distutils); this will fix the compiling error "AttributeError: 'Extension' object has no attribute 'extra_c_compile_args'" with numpy>=1.22.0